### ISSUE TITLE
Ventilation Control?

### ISSUE THREAD

**Issue by nrus2222** [SANdood/Ecobee-Suite#11]
I have fresh air vent damper control connected across ACC switched output of Ecobee 4 (instead of humidifier/dehumidifier). It’s configured on ecobee, and shows when it’s running in ecobee app, as well as allowing manual running of ventilator and setting of minimum ventilator on time. 

I don’t see any support for this ventilator option in your suite. Am I missing something, or is this option not yet supported?

**Comment by SANdood** [comment]
Hmmm. You are the first one to mention that. I will look into reporting when it is on - I’m not sure I can do anything to control it. 

Give me a few days...

Thanks!
      Barry

**Comment by nrus2222** [comment]
Thanks, Barry. That would be great. Really appreciate all your efforts.

Best Regards,
Noel

On Nov 26, 2018, at 5:22 AM, Barry Burke <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, so adding support for Ventilators/ERV/HRV is non-trivial. Not impossible, but it requires some significant coding on my part. It will take some time for me to figure out the changes required and implement them.

I may add the commands/status first and make them available via the API, then go back and add the visible integration to the GUI. If so, I'll let you know...

**Comment by arcegabriel** [comment]
I am on the same boat. I have an ecobee 4 and have an HRV
I would love to be able to control it (for instance turn HRV when bathroom fan is on)
Thanks for the great work

**Comment by SANdood** [comment]
I haven't made much progress on this as an integrated solution.

BUT!!! My new Universal Ecobee Suite introduces the `setEcobeeSettings()` command, perhaps you can use that to control your ventilator directly using WebCoRE?

https://community.smartthings.com/t/beta-universal-ecobee-suite-for-smartthings-hubitat-free/162953

**Comment by arcegabriel** [comment]
When would you be releasing 1.7 ?
I am still getting familiar with 1.6 (installed on Wednesday) so want to soak it a little before joining a beta

**Comment by SANdood** [comment]
1.7 will probably be released over the weekend, unless I find some crazy bug. I still have the documentation to update, however.

The UI is the same in 1.6 and 1.7 - all the changes are under the covers.

**Comment by arcegabriel** [comment]
Ok, I have 1.7 and is up and running
As far as original post, alternative cooling using HRV when outside temp is lower than inside (ecobee4)
I have done only a couple of very simple webcore scripts (turn on bathroom fan when humidity is higher than house). This was modifying a script I found elsewhere. 
I have a couple of couple of problems with this alternative cooling script. I dont know the logic (other than basic outside air is cooler than inside air -> start). 
Also I am bit intimidated on using the setecobeesettings() command for this purpose. (I am not a programmer)
Hoping I  can across some inspiration or maybe another person with same need can start and I can help testing.

**Comment by SANdood** [comment]
You will probably have more luck finding inspiration by following the Ecobee Suite thread on the SmartThings Community...
