### ISSUE TITLE
Feature Request: Smart Room helper use motion sensor to activate

### ISSUE THREAD

**Issue by StrykerSKS** [SANdood/Ecobee-Suite#12]
I've finally installed your updated system to replace mine since I haven't worked on it in forever. Plus I'm now installing Keen vents in my house.

For the Smart Room helper app I want to be able to use motion as a way to activate the room rather than an open door. If I get some time I might take a stab at making the updates, but just in case you have time or the inclination then I wanted to add it to the list.

**Comment by SANdood** [comment]
It's a good idea, but a little tricky. You'll need to use some sort of timer to maintain that the room is still occupied, perhaps connected to Night/Sleep to keep the room activated when someone is sleeping. The current implementation realizes that once motion is detected while the door is closed, the room remains occupied until (after) the door is opened.

I've also installed Rooms Manager (https://community.smartthings.com/t/rooms-manager-smarter-rooms-personalized-home-automation-with-occupancy/102576) it does a pretty good job of figuring out when a room is occupied and already has timeouts built in...

**Comment by StrykerSKS** [comment]
Good points.

I'll have to think about it a bit more I guess. For me, I don't need it to be super accurate since the room is usually not used, but when it is used it is almost always for overnight guests. 

I'll have to take a look at Rooms Manager as well.

**Comment by SANdood** [comment]
Closing this for now - if you have specific suggested changes, please open another Issue.
