### ISSUE TITLE
removeSensorFromSleep() does not work

### ISSUE THREAD

**Issue by dds82** [SANdood/Ecobee-Suite#19]
Attached WebCoRE piston does nothing. Expected: the sensor should be removed from the Sleep comfort setting.
![download](https://user-images.githubusercontent.com/47287470/57986994-cf433400-7a49-11e9-88b3-011f02163f29.png)

addSensorToSleep() works fine. Only removal does not work.

Ecobee suite 1.7.01 running on SmartThings

**Comment by SANdood** [comment]
I suggest upgrading to the latest, then send me the Live Log for the Sensor, the Thermostat, and for Ecobee Suite manager - there should be an error in at least one of those. Once I can see the error, I can fix it quickly...

**Comment by dds82** [comment]
I think I updated to the latest - it still says version 1.7.01 in my SmartThings app, but in the IDE it says no code is out of date.

How do I get you the logs you need?  Where do I find them?

**Comment by dds82** [comment]
I figured out how to get them.  Here goes a big data dump.

I wrote another test piston to exercise addSensorToSleep().  Here is the live logging from that one:

**Sensor**

`eb98ce07-42c2-4586-98c1-8f39c5dab413  9:54:20 AM: info Updated 5 objects (20ms)
eb98ce07-42c2-4586-98c1-8f39c5dab413  9:54:18 AM: info Refreshed - executing parent.pollChildren(511841176372)
eb98ce07-42c2-4586-98c1-8f39c5dab413  9:54:13 AM: info addSensorToProgram(sleep) - Succeeded`

**Thermostat**

`0e5139c2-3c3b-49da-a8d5-2bd0c0d25260  9:55:30 AM: info Updated 4 objects (126ms)
0e5139c2-3c3b-49da-a8d5-2bd0c0d25260  9:54:20 AM: info Updated 4 objects (129ms)`

**Ecobee Suite Manager**

`31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:30 AM: trace Updates sent (307 / 1106ms)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:30 AM: info Polling thermostat Thermostat (511841176372) completed
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:30 AM: info Updates for 1 sensor (Den)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:30 AM: info Updates for 1 thermostat (Thermostat)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:29 AM: info Requesting ( equipmentStatus runtime sensors ) for thermostat Thermostat (511841176372)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:55:29 AM: info Polling thermostat Thermostat (511841176372)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:29 AM: trace No updates...
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:23 AM: trace No updates...
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:20 AM: trace Updates sent (388 / 1267ms)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:19 AM: info Polling thermostat Thermostat (511841176372) completed
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:19 AM: info Updates for 3 sensors (Elana, Guest Room, Thermostat)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:19 AM: info Updates for 1 thermostat (Thermostat)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:54:18 AM: info Polling thermostat Thermostat (511841176372)`

The following is the live logging from exercising removeSensorFromSleep():

**Sensor**

`2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:45 AM: info ╔ Event processed successfully (938ms)
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:45 AM: trace ║╔ Execution stage complete. (873ms)
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:45 AM: trace ║║ Executed [GuestRoomES].removeSensorFromSleep (858ms)
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:45 AM: debug ║║ Executed physical command [GuestRoomES].removeSensorFromSleep() (855ms)
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:44 AM: debug ║║ Cancelling statement #1's schedules...
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:44 AM: trace ║╚ Execution stage started
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:44 AM: trace ║ Runtime (35993 bytes) successfully initialized in 37ms (v0.3.10b.20190514) (60ms)
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:44 AM: debug ║ RunTime Analysis CS > 13ms > PS > 37ms > PE > 9ms > CE
2e95cd7f-bb5d-451d-b557-45b7d33557dc  9:57:44 AM: info ╚ Received event [Home].test = 1558360664108 with a delay of 0ms
eb98ce07-42c2-4586-98c1-8f39c5dab413  9:57:45 AM: error java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class org.codehaus.groovy.grails.commons.DefaultGrailsApplication @line 4462 (deleteSensorFromProgram)
eb98ce07-42c2-4586-98c1-8f39c5dab413  9:57:44 AM: info Updated 1 object (31ms)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:57:44 AM: trace deleteSensorFromProgram(GuestRoomES,Thermostat,rs:103,sleep)
 9:57:38 AM: info Waiting on events...
 9:57:38 AM: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
 9:57:38 AM: info This console provides live logging of your SmartThings.`

**Ecobee Suite Manager**

`31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:31 AM: trace Updates sent (315 / 2493ms)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:31 AM: info Polling thermostat Thermostat (511841176372) completed
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:31 AM: info Updates for 1 sensor (Guest Room)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:31 AM: info Updates for 1 thermostat (Thermostat)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:29 AM: info Requesting ( equipmentStatus runtime sensors weather ) for thermostat Thermostat (511841176372)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:58:29 AM: info Polling thermostat Thermostat (511841176372)
31106fb9-de29-416e-a5c4-0e28e4e7158a  9:57:44 AM: trace deleteSensorFromProgram(GuestRoomES,Thermostat,rs:103,sleep)`

**Thermostat**

`0e5139c2-3c3b-49da-a8d5-2bd0c0d25260  9:58:31 AM: info Updated 4 objects (118ms)`

This is probably the error you're looking for:

`eb98ce07-42c2-4586-98c1-8f39c5dab413  9:57:45 AM: error java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class org.codehaus.groovy.grails.commons.DefaultGrailsApplication @line 4462 (deleteSensorFromProgram)
`

**Comment by SANdood** [comment]
I suggest doing “Update from Repo” for both SmartApps and Device Handlers. Double check that you are using the ‘master’ fork, and not ‘universal dev’. 

Thanks!
      Barry

**Comment by dds82** [comment]
Yep.  I did all that first thing.

See my more recent comment.  I found the error you need.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SANdood** [comment]
Just FYI, you aren't running the latest code - the error is from the 1.7.01 version of ecobee-suite-manager.groovy, while the latest (until just now) was 1.7.05. All 14 files have been updated since last Friday's release of 1.7.00.

You can see the latest versions for each file here: https://github.com/SANdood/Ecobee-Suite/tree/master/smartapps/sandood

I just posted version 1.7.06 of both ecobee-suite-manager.groovy and ecobee-suite-thermostat.grovy. You will need to update at least these 2 files to get the fix, but I suggest you update all of them to avoid a plethora of (now known) errors and odd behaviours.

**Comment by dds82** [comment]
I have a strange issue where I do an update and publish from GitHub in the
IDE and a short while later it's as if I never did it. Have you ever heard
of that before?

**Comment by dds82** [comment]
Updated to 1.7.06.  Confirmed fixed.

**Comment by SANdood** [comment]
Nope - shouldn't happen. Contact SmartThings support...
