### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by maxmokeyev** [SANdood/Ecobee-Suite#2]
When trying to authorize Ecobee Suite from the mobile app, after entering ecobee credentials and clicking "Accept" i get en error message saying "We are sorry but we are unable to complete your request". Then an error page gets loaded with:
{"error":true,"type":"java.lang.reflect.UndeclaredThrowableException","message","An unexpected error ocurred."}

**Comment by mfbarnes** [comment]
I am also having the same issue.  I hadn't updated to the new ecobee Suite yet and thought maybe that was the problem.  I just finished updating all of my device handlers and smart apps to the new 'suite' version and am still getting the same message.  Oddly, the first time I got the message it said:
{"error":true,"type":"com.netflix.hystrix.exception.HystrixRuntimeException","message":"An unexpected error occurred."}
I thought the 'Netflix' thing was weird so I closed Netflix on my phone, tried again and got the same message as maxmokeyev.

**Comment by SANdood** [comment]
Multiple sources are reporting issues with SmartThings connecting to the Ecobee Cloud/API server - it is not just my Ecobee Suite. 

Thanks!
      Barry

**Comment by maxmokeyev** [comment]
Thanks Barry. I checked ecobee status lage, but there were no issues listed, that's why I decided to post here. Hopefully they will resolve it soon.

**Comment by SANdood** [comment]
Thanks, Max!

      Barry
