### ISSUE TITLE
Sensor device tiles in new SmartThings app (not classic) show motion status instead of temperature

### ISSUE THREAD

**Issue by dds82** [SANdood/Ecobee-Suite#20]
It's much more useful to see room temperature than motion status at a glance.  Is it possible to change the sensor tiles to show temperature instead of motion status?  (Note: the thermostat tile does show temperature.)

**Comment by SANdood** [comment]
Sorry, no can do. Wish I could. 

Samsung/SmartThings have not released a vid that offers temp as the primary display. The fact that the thermostat even works with Samsung Connect is sheer luck.

If you can find a vid that shows temp on main and motion as secondary (or get SmartThings to create one), let me know and I'll change it in a heartbeat.
