### ISSUE TITLE
Thermostat DTH number of attributes may be causing an issue with webCoRE loading the list of devices.

### ISSUE THREAD

**Issue by anders0ndg** [SANdood/Ecobee-Suite#21]

**Comment by SANdood** [comment]
Interesting.

Thank you for reporting the issue. I would like to do what I can to mitigate the situation.

Could you please provide more information:

- Which platform (SmartThings or Hubitat) and software versions?
- Which version(s) of WebCoRE?
- How did you determine this?
- Do you know for a fact it is the number of Attributes and not the number of Commands that ES provides?
- How many thermostats and sensors are you using with Ecobee Suite?
- How many/what other devices are you running on this Hub?
- Have you contacted the WebCore developers about this limitation of their product?
- Do you have suggestions on how to address this limitation?

**Comment by anders0ndg** [comment]
Yes... please see the following:

Which platform (SmartThings or Hubitat) and software versions? SmartThings
Which version(s) of WebCoRE? V0.3.10c
How did you determine this? If I remove the Thermostats from WebCoRE, the issue with WebCoRE loading the device list no longer exists.
Do you know for a fact it is the number of Attributes and not the number of Commands that ES provides? I'm fairly certain it is due to the number of thermostat attributes
How many thermostats and sensors are you using with Ecobee Suite? 3 - Thermostats, 12 - Sensors
How many/what other devices are you running on this Hub? 144 - Combination of switches, dimmers, lamps, cameras, and integration with my Honeywell Alarm System thru an AlarmDecoder interface.
Have you contacted the WebCore developers about this limitation of their product? I have not
Do you have suggestions on how to address this limitation? Unfortunately, I do not. I posted this mainly as information in case other WebCoRE users experienced the same issue.

I honestly don't know if there is anything you can do to solve this issue, other than to publish a "Thermostat lite" DTH that has a scaled down list of attributes. I believe this is a known issue with WebCoRE, but I'm not sure what the device attribute threshold is.

Thank you for the great work!!!
