### ISSUE TITLE
Contacts and Switches Helper Notifications

### ISSUE THREAD

**Issue by anders0ndg** [SANdood/Ecobee-Suite#22]
What is the expected notification behavior for the Contacts and Switches Helper? I currently have a Helper set to monitor door and window contacts and turn off the HVAC system after a contact has been open for 10 minutes using the following options:

- Turn off HVAC? is Enabled
- Run HVAC Off Actions when any of the contacts are open? is Enabled
- Delay time (in Minutes) before turning off HVAC or Sending Notification is set to 10
- Delay time (in Minutes) before turning HVAC back on or Sending Notification is set to 1
- Select which actions to take is set to Notify and HVAC Actions

With these settings I am receiving an event notification every time a door/window contact opens or closes. Is that correct?

**Comment by SANdood** [comment]
Shouldn't be happening, but I will post a fix for it in a few minutes.

**Comment by anders0ndg** [comment]
Problem solved. Thank you for the fix!
