### ISSUE TITLE
Setting fan is not working

### ISSUE THREAD

**Issue by josephnad** [SANdood/Ecobee-Suite#23]
Setting fan mode is not working because of an error in setThermostatFanMode().
There is a typo in ecobee-suite-thermostat.groovy lines 2737 and 2740. The variable name should be currentThermostatHold with 2 r's instead of 3.

Once I replaced with correct variable name, fan on ecobee thermostat is now changing correctly, and ST live log is not showing this error anymore:

error groovy.lang.MissingPropertyException: No such property: currrentThermostatHold for class: script_dth_XXX @line 2728 (setThermostatFanMode)

**Comment by SANdood** [comment]
Fixed in Thermostat v1.7.15 and released - thank you very much!!!
