### ISSUE TITLE
Contacts & Switches Helper Actions 

### ISSUE THREAD

**Issue by anders0ndg** [SANdood/Ecobee-Suite#24]
I currently have a Contacts & Switches Helper set to monitor door and window contacts and turn off the HVAC system after a contact has been open for 10 minutes using the following options:

- Turn off HVAC? is Enabled
- Run HVAC Off Actions when any of the contacts are open? is Enabled
- Delay time (in Minutes) before turning off HVAC or Sending Notification is set to 10
- Delay time (in Minutes) before turning HVAC back on or Sending Notification is set to 1
- Select which actions to take is set to Notify and HVAC Actions

With these options the HVAC Action (Off) is triggering immediately when a monitored contact is opened.

Thanks in advance for the help.

**Comment by SANdood** [comment]
Which version of Contacts & Switches? Which version of ES Manager & Thermostat? What hub platform? How many contacts/switches do you have configured? Did you edit/save the configuration after you last upgraded the code?

FYI - As noted in the documentation, I use the community forums on both SmartThings and Hubitat for support requests - I rarely look here for Issues. I would appreciate it if in the future you logged your issues in one of those two forums (doing so at least answers the question of "What hub platform?")

Thanks!

**Comment by anders0ndg** [comment]
Yes sir. I apologize. SmartThings is the platform. I'm on V2. The following are the ES versions:

Manager: 1.7.19
Thermostat: 1.7.16
Open Contacts: 1.7.16

I have 6 - contacts that are monitored and 3 - thermostats configured. Yes, I did edit/save the configuration after updating. 

Thank you!
