### ISSUE TITLE
Keen Vent issues

### ISSUE THREAD

**Issue by sangdrax8** [SANdood/Ecobee-Suite#26]
I am having some issues with 2 Keen vents I just connected to my system.  First, I believe there is an issue with Keen vents and correctly opening.  Even if just using smartthings tiles, I get it to close every time, but when I press open nothing happens.  However if I adjust it by the percentage, it works as expected.  I mention this because it could be some of the confusion with your suite.  To try and fix this, I have used my vents as "generic dimmers" in your suite, however I still have some issues.  To try and help verify, I have run through these following things with a dimmer switch and a LED to confirm it is at least consistent with my vents.

- Turning off the vent (or light) does not obey the minimum levels.  Every time it turns it off fully (or in the vent case closes it fully).
-  Turning on (or opening) the vent appears to just issue the "on" command, instead of setting the level to 100%.  I think due to the apparent bug in the keen vents, this causes them to not actually open.  Testing with my light, it does in fact turn on but at what ever the last level was.  Therefore even the light doesn't go to 100% with called for.  It is worth noting that the vent/light is fully off (due to bullet 1) rather than being on but at the minimum level.  So I can't test a state where it is at the minimum and receives an "on" signal.  Perhaps if that were the case, it would HAVE to adjust the percentage to 100%.

I would appreciate any assistance here.  I would love to just be doing this wrong if someone can correct my error.  Right now I am considering trying to write a WebCORE piston, but there are so many things yours already does, such as following the set points of specified thermostats.

**Comment by sangdrax8** [comment]
A little further testing, I commented out the check for hasCapability('switchLevel'), and my dimmer switch now turns off to the set minimum.  So for my LED test, the setLevel works, even when switchLevel doesn't seem to resolve to true.  I can't test the vent at this time, but I hope to test turning back on and the vents to confirm if this is true for those cases as well.

**Comment by SANdood** [comment]
I guess I don't understand what you are saying - that your Keen vents respond to setLevel(), but do not support the capability switchLevel?

If so, I'll have to think about how to address this. Perhaps I need to use "hasCommand" instead of hasCapability...

**Comment by SANdood** [comment]
Try this version and see if it works better (note: this is in a development branch for now):

https://raw.githubusercontent.com/SANdood/Ecobee-Suite/universal-dev/smartapps/sandood/ecobee-suite-smart-vents.src/ecobee-suite-smart-vents.groovy

**Comment by sangdrax8** [comment]
After loading this one, I had a vent that was already closed.  I turned up the thermostat to cause it to heat, and then went back and saw the vent helper had (open) next to the name.  However the vent was still closed. 

I can't very easily cause the conditions to switch back and forth for testing quickly, but so far it does not seem to be working as intended.

**Comment by SANdood** [comment]
To figure out what is going on, you will need to capture Live Logging while you are testing. In this case, we need to know what the Smart Vent helper  wrote into the Live Logs, as well as what the Vent device itself logged. Since vents are battery powered, they sometimes take a while to respond to commands...the hub has to wait for them to wake up in order to send commands...

Also, it is easier for me if you could report issues via the appropriate platform: either the SmartThings Community (https://community.smartthings.com/t/release-universal-ecobee-suite-version-1-7/163929 ), or Hubitat Community (https://community.hubitat.com/t/release-universal-ecobee-suite-version-1-7/15813). I pretty much just use GitHub as the repository...

**Comment by sangdrax8** [comment]
Sure, I'll go to the community and re-post there after I look for some logs. thanks!

**Comment by SANdood** [comment]
Fixed after discussions on the Community.
