### ISSUE TITLE
Hubitat: Feature Request: Support Hubitat Virtual Thermostats

### ISSUE THREAD

**Issue by Dannyzen** [SANdood/Ecobee-Suite#29]
In the use case of Vents, I use virtual thermostats to keep the temperature of each vent (zone) to be different. I was wondering if that use case may be supported by allowing virtual thermostats to be used in the Smart Vents & Switches app or as an alternative, a feature that allows a specific setpoint to be set for each vent.

**Comment by SANdood** [comment]
First, you'll find the community discussions for Ecobee Suite much more productive - lots of help from other users: 
* Hubitat: https://community.hubitat.com/t/release-hubconnect-share-devices-across-multiple-hubs-even-smartthings/12028
* SmartThings: https://community.smartthings.com/t/release-universal-ecobee-suite-version-1-7/163929

Secondly, that is exactly what the **Smart Vents & Switches Helper** delivers:

> This Helper dynamically adjusts the vent open percentage based on room temperature relative to an Ecobee Suite Thermostat's setpoints, or to ***pre-defined cooling & heating setpoints.*** It will also automatically register the room's Ecobee Suite Sensor(s) to the chosen ES Thermostat programs while active, and unregister while the Helper is Paused. There should be one instance of this Helper for each room with an adjustable vent, ideally (but optionally) with an Ecobee Suite Sensor in the room (multiple sensors will be averaged).

Which virtual thermostat are you using - I'll have a look to see if it's easy to add support for that as another option for Smart Vents...

**Comment by Dannyzen** [comment]
Thank you very much for the pointer, I'll check the community posts.

I'm using the hubitat virtual thermostat (native). https://community.hubitat.com/t/updated-average-all-temperature-humidity-illuminance-ambient-pressure-motion/3539/95 uses it from my understanding. 

(https://github.com/CobraVmax/Hubitat/tree/50a4a467bec89d088717fc21b9712aa52345c19d/Apps/Average%20All) for ref as the original author closed sourced the apps.

**Comment by SANdood** [comment]
Closed - Feature included in Version 1.8.01
