### ISSUE TITLE
Smart Circulation cannot be installed

### ISSUE THREAD

**Issue by squizzeak** [SANdood/Ecobee-Suite#3]
I just uninstalled the DH's and smartapps from the old repo and installed from this fork, and when attempting to install the Smart Circulation helper I get the following error:

582196dd-43a4-4020-aeaf-b926789d8f6e  1:33:34 PM: error java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty. @line 148 (getProgramsList)

I attempted to work around it by hardcoding the programs list, but I encountered further difficulties when the thermostatOperatingState was showing as "null" and no changes were being made to the fan time.

**Comment by SANdood** [comment]
Weird – yours is the second report of a missing programsList. This is supposed to be defined in the thermostat device – can you please verify whether or not “programsList” appears in the Current States for the thermostat device (click on the device in the My Devices page to see all the states).

 

Thanks!

**Comment by squizzeak** [comment]
Here's all of it:

`temperature: 73
humidity: 35
motion: inactive
thermostatFanMode: circulate
heatingSetpointRange: [45.0, 79.0]
supportedThermostatFanModes:
[on, auto, circulate, off]
supportedThermostatModes:
[off, heat, auto]
checkInterval: 3900
currentProgramName: Hold: Temp
currentProgramId:
weatherSymbol: 2
timeOfDay:
temperatureDisplay: 73°
equipmentOperatingState: heat pump hum
heatMode: true
autoMode: true
heatStages: 1
hasBoiler: false
heatRangeLow: 45.0
coolRangeHigh: 92.0
heatingSetpointMin: 45.0
coolingSetpointMax: 92.0
heatRange: (45..79)
fanMinOnTime: 5
thermostatOperatingStateDisplay: heating
thermostatFanModeDisplay: circulate
thermostatTime: 2018-04-04 13:37:32`

This would also help explain why thermostatOperatingState is null; only the Display variant is present in the object.

If it helps debug, I did elect to expose the temp sensor of the thermostat separately.

**Comment by SANdood** [comment]
Odd…you are missing a TON of additional attributes.

Can you please tell me the version numbers as reported by Ecobee Suite Manager (top of the settings page) and Ecobee Suite Thermostat (click on the Gear icon for the device)?

**Comment by squizzeak** [comment]
"Welcome to Ecobee Suite Manager, version 1.4.16"
"Ecobee Suite Thermostat, version 1.4.07"

**Comment by SANdood** [comment]
I’ve found the problem – working on fixing it now…

**Comment by SANdood** [comment]
Please get the latest versions from this GitHub repository

**Comment by squizzeak** [comment]
That did the trick.  Thanks for the quick fix!
