### ISSUE TITLE
"You don't have access to SANdood/Ecobee-Suite"

### ISSUE THREAD

**Issue by ot0tot** [SANdood/Ecobee-Suite#30]
I'm trying to link my IDE with the Ecobee Suite repository following the instructions here:
https://github.com/SANdood/Ecobee-Suite#installing-using-github-integration-recommended-method

> Login to the IDE at ide.smartthings.com
Click on My Locations at the top of the page
Click on the name of the location that you want to install to
Click on the My Device Handlers tab
Click Settings
Click Add new repository and use the following parameters:
Owner: SANdood
Name: Ecobee-Suite (note that the hyphen is required)
Branch: master
Click Save

And when I click Save I get an error: "You don't have access to SANdood/Ecobee-Suite"

Any ideas?

**Comment by ot0tot** [comment]
I solved this by deauthorizing and then reauthorizing GitHub integration.

**Comment by dglasgo1** [comment]
Before I do this, just curious, do you lose the connection of your other handlers connected to Github?
