### ISSUE TITLE
Flair vent support

### ISSUE THREAD

**Issue by kmickeletto** [SANdood/Ecobee-Suite#4]
I know this isn't an issue, but was wondering if and when Flair smart vent support might be added?  I have about 14 of these currently in use and will be happy to provide any test cases and will be happy to do any legwork required to help out.

Thanks for a great solution!!

**Comment by SANdood** [comment]
You can use the Smart Switxh automation with any device that appears as a “dimmer” - have you tried that?

Thanks!
      Barry
