### ISSUE TITLE
Contacts & Switches helper is broken/won't save

### ISSUE THREAD

**Issue by reijop** [SANdood/Ecobee-Suite#40]
Version 1.8.42, updated from master today.
 

Installing a new Contacts & switches helper from either Smart things app.

From smart things logs:
```
d1b0e3a6-a451-410f-99cb-4d4be203d28b 12:11:30 PM: error java.lang.NullPointerException: Cannot invoke method capitalize() on null object @line 1521 (updateMyLabel)

d1b0e3a6-a451-410f-99cb-4d4be203d28b 12:11:30 PM: info Ecobee Suite Contacts & Switches Helper, version 1.8.22 on SmartThings - Initializing...

d1b0e3a6-a451-410f-99cb-4d4be203d28b 12:11:30 PM: trace Installed with settings [offDelay:5, addThePrefix:false, tempDisable:false, whichAction:Notify Only, hvacOff:false, includeDelays:true, quietTime:false, contactSensors:[Back Door], customTstat:custom, contactOpen:true, debugOff:false, theThermostats:[EcobeeTherm: Thermostat], customContact:doors, pushNotify:true, adjustSetpoints:false, onDelay:0, customPrefix:custom, customPrefixText:Ecobee Door Watcher:, speak:false, minimize:false, useSensorNames:true, infoOff:false, customTstatText:HVAC]
```

UI properly works up until hitting 'save', then the above errors from ST logs and a red banner in the app with 'An unexpected error occured'

I did not want to sort out this line.  My java is terrible:
https://github.com/SANdood/Ecobee-Suite/blob/04f8b7b5c0b70550afa78115c0c1e39f6485ab96/smartapps/sandood/ecobee-suite-open-contacts.src/ecobee-suite-open-contacts.groovy#L1528

**Comment by SANdood** [comment]
You are apparently running version 1.8.22 of the Contacts & Switches Helper. I am pretty sure I fixed that problem in the current version (1.8.23)...please install that version and open a new ticket if it still doesn't work...
