### ISSUE TITLE
Oauth to API

### ISSUE THREAD

**Issue by jsarcone** [SANdood/Ecobee-Suite#41]
I was on the phone with Ecobee support I'm getting an authentication fail on the API login screen and the application was disauth too. Ecobee support the method that is being used is not long support. There this is a "new" process. Some of the major application vendors have it like Google and Amazon. The application will get authorized at this time. I have Support information that I can share directly to you.

**Comment by SANdood** [comment]
Support for the "new" OAuth was implemented in August 2020.
