### ISSUE TITLE
Mode Helper Smart App Requiring Changes to Switches

### ISSUE THREAD

**Issue by surefoot** [SANdood/Ecobee-Suite#42]
V1.8.44. Helper Smart App for "Mode/Routine/Switches/Program" now requires "Change These Switches" to be assigned in order to save the Helper Smart App.  This is not always desired and should be an optional action.

**Comment by SANdood** [comment]
Fixed, but the requirement should only have been if neither a Mode change nor a Program Change was requested.

**Comment by surefoot** [comment]
Thanks Barry!

**Comment by surefoot** [comment]
Barry,

 

Do you have any recommendations on device handlers for the Keen Home vents?  The default DTH’s provide temperature and pressure updates every minute (which I don’t think I’m using), and I suspect are causing latency on my zwave network.  

 

Seems like these two developers released a DTH for Keen. Are you using one of them?  Did you write your own?

 <https://community.smartthings.com/u/johnconstantelo> johnconstantelo

 <https://raw.githubusercontent.com/constjs/jcdevhandlers/master/devicetypes/jscgs350/my-keen-home-smart-vent.src/my-keen-home-smart-vent.groovy> https://raw.githubusercontent.com/constjs/jcdevhandlers/master/devicetypes/jscgs350/my-keen-home-smart-vent.src/my-keen-home-smart-vent.groovy 60

yvesracine’s DTH:

 <https://raw.githubusercontent.com/yracine/keenhome.device-type/master/devicetypes/keensmartvent.src/keensmartvent.groovy> https://raw.githubusercontent.com/yracine/keenhome.device-type/master/devicetypes/keensmartvent.src/keensmartvent.groovy 30

 

Regards,

Brad

**Comment by SANdood** [comment]
Keen vents are ZigBee, not Z-Wave, so it is unlikely they are interfering with your Z-Wave devices.

As for the driver, I use the one included in this repository here: https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/Keen%20Home%20Smart%20Vent.groovy

It has an option to disable temp & pressure reporting.

**Comment by surefoot** [comment]
Barry,

 

Thanks for the help on this and for putting together a really great product.  My Ecobee & Smart vents are working great.  

 

I sent you a donation today for all your hard work.  I appreciate your efforts.

 

Regards,

Brad

**Comment by surefoot** [comment]
Barry,

 

1.	I can’t seem to figure out how to add this Keen device handler through GitHub.  It doesn’t show up in the SANdood/Ecobee-Suite (master) repository, and I’m not sure what other repository name could work.  The rest of the Ecobee Suite seems to be accessible and update quite nicely.  

https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/Keen%20Home%20Smart%20Vent.groovy

I’ve manually pasted it in, but would prefer to link it though GitHub incase you make any changes.  

 

2.	I’ve been thinking about migrating from Smarthings to Hubitat as Hubitat seems to be faster than my Smartthings V2 hub in executing Alexa integrations. But Hubitat lacks the GitHub integration, which seems to make it hard to keep the apps up to date.  

I know you migrated recently.  I was curious why you decided to transition and what your experience has been.  Are you glad you made the shift?  

 

Regards,

Brad

**Comment by audiofreak9** [comment]
For #2 use the [Hubitat Package Manager](https://community.hubitat.com/t/beta-hubitat-package-manager/38016).  It tracks and will even auto-update apps if you wish. 

For me there was no question that Smartthings was no longer allowing me to do what I wanted to do with my home automation.  They removed Echo Speaks and my own Groovy Code was no longer easily accessible.  I also had way to many devices (60+) for Smartthings to deftly handle, and with Groovy going away in the near future it was an easy decision.  I migrated to HE this past September and never looked back.
