### ISSUE TITLE
generateEvent Null Pointer Error

### ISSUE THREAD

**Issue by jlkweb12** [SANdood/Ecobee-Suite#43]
I am seeing this error in the logs.

I see that it connected to my thermostats and can see my sensors. However no "Things" appear in my list. I see this error in the logs.

 error java.lang.NullPointerException: Cannot invoke method generateEvent() on null object @line 2166 (doCall)

**Comment by SANdood** [comment]
Please verify your installation - it has been reported that the SamrtThings/GitHub integration has not been updating the DTH's properly. Make sure that 
* everything is installed, 
* each module is the latest from the Ecobee Suite GitHub repository
* ALL the files have been published

Then, if it still doesn't work, uninstall and then redo the install from scratch.

PS - posting on the appropriate thread in the SmartThings or Hubitat Communities will often get you faster responses from other users...
