### ISSUE TITLE
Mode/Routine/Swiches/Program Helper Won't Trigger on Routine Execution

### ISSUE THREAD

**Issue by surefoot** [SANdood/Ecobee-Suite#47]
After migrating to the new Smarthings Samsung Connect App Mode/Routine/Swiches/Program Helper no longer Triggers on Routine Execution.  It still works just fine on a Mode change trigger.  
Ecobee Suite Manager Version 1.8.47 
Firmware: 000.031.00004.  
Controller Version: 2.1.15-6

**Comment by SANdood** [comment]
The new SmartThings no longer supports Routines - at all. They all get changed to Scenes when you migrate.

The solution is to use a Virtual Switch: have the scene turn on the "Home" Virtual Switch (for example), and have the Helper take action based on Home being turned on. You will also want the Scene to turn off "Away" and "Night" switches when it turns on Home.

**Comment by surefoot** [comment]
Barry,

 

The switch is a good work around.  Might be a good idea to not allow it to accept an automation/routine as a trigger then.  Or at least provide a warning.  Currently you can set it up, but it just won’t trigger.

 

Regards,

Brad

**Comment by SANdood** [comment]
I will consider removing it when SmartThings fully removes support for Routines. They are still supporting them for Classic users, it appears.
