### ISSUE TITLE
Not seeing door sensor

### ISSUE THREAD

**Issue by PhoenixFireGames** [SANdood/Ecobee-Suite#49]
I have a door sensor but it doesn't see it?

**Comment by SANdood** [comment]
Ecobee Suite only supports Ecobee thermostats and Ecobee Room temp/occupancy sensors.  It does not support any other Ecobee devices. If your hub offers support for these, you can run your hub’s native support for everything else, if you would like. I *may* add support for Ecobee Switches at some point, but For technical reasons, I sincerely doubt I will ever add support for the door (contact) sensors.
