### ISSUE TITLE
Hubitat:  Temperature Change Momentary Turn On/Off

### ISSUE THREAD

**Issue by Djackson0810** [SANdood/Ecobee-Suite#50]
I have a rule that sets both of my HVAC units to 78 degrees at night.  Normally the house is at the degrees so the units are not on.  However, when the rule runs the units kick on momentarily then shut off.  This does not happen if I am using the Hubitat built in Ecobee App.  Could this be an issue with the Ecobee Suite?

**Comment by SANdood** [comment]
I am unable to replicate. Please send me a copy of your Rule, and the specifics on how to replicate, and I'll see what I can do...

**Comment by Djackson0810** [comment]
Hi... I actually forgot that I submitted this ticket.  I have not been able to get this issue to replicate either.  Maybe it was a fluke or something going on with Ecobee at the time.  I’m going to go ahead and close this issue.  Thanks for the response and the great tool.
