### ISSUE TITLE
SmartThings: ES set thermostatOperatingMode to "offline"

### ISSUE THREAD

**Issue by loverso** [SANdood/Ecobee-Suite#53]
I had a webCoRE piston that fired when thermostatOperatingMode had the value "offline", which isn't one of the allowed values for that capability.  Some discussion here:  https://community.webcore.co/t/thermostatoperatingstate-missing-an-enumeration-offline/18197

Background: my Ecobees were set to "off" as I wasn't running the HVAC at all.  My piston checked checked if the operating mode was neither of 'idle' or 'fan only', and then if there were windows open, would send me a notification. I got the notification telling me the operating mode was "offline".

**Comment by SANdood** [comment]
Per the discussions, there is no defined authority that precludes an operating state/mode of "offline." Checking for the specific operating modes that you want to take action for is a more robust way of coding the objective than simply "other than".
