### ISSUE TITLE
Air Quality and Smart Circulation

### ISSUE THREAD

**Issue by reijop** [SANdood/Ecobee-Suite#54]
Feature request:

Smart Circulation based on Air Quality index inside and/or outside. I am thinking about the ongoing fires on the west coast of the US and general solutions. Homes with a central fan have filters, this can be better than nothing.

Looking through the SmartThings API, I see a capability type for AQI: https://docs.smartthings.com/en/latest/capabilities-reference.html#air-quality-sensor, and I have successfully used @jschlackman's /Airnow to setup an 'outdoor' sensor.  I'm groovy-deficient but will happily take a whack at a PR for this, unless someone else with more knowledge can see a quick and easy path.

Ideally, I was envisioning two modes, one based on the outside air quality with no internal sensor, and a two-sensor mode that would run less often based on the actual inside AQI.  For my purposes, I'd just like to see the smart fan run > 45m/hr when the general outside AQI is above 200.  If I had an internal sensor, I'd like to use that to ramp the smart circulation time down as the AQI approaches a desired 'set' level.

If nothing else - Maybe I can write a smart app to interface with your smart-circulation helper?  Could I send the helper or thermostat control the number of minutes per hour to run somehow?

**Comment by SANdood** [comment]
Reasonable request, but it is unlikely that I will be able to tackle this any time soon.

I will note that this is complicated by the observation that different AQI sensors report different values for the same air, and that there are different AQI standards in the USA, Canada and overseas.
