### ISSUE TITLE
Thermal Comfort GUI error

### ISSUE THREAD

**Issue by Mythris29** [SANdood/Ecobee-Suite#58]
This happened to me when I used smart things as well just FYI.

So, when I try to configure the Thermal comfort helper if I try to select anything in a drop-down menu the whole GUI disappears, and I can't do anything else with it. I'm attaching a screenshot to try to explain what I mean. Right now I'm using Hubitat and going through it's local web interface but I've also had this problem when I used Smartthings previously and it also affects the mobile app version (though on Hubitat it's just the web version still).
![ecobeeerror](https://user-images.githubusercontent.com/15204330/98497312-d55e3f00-2200-11eb-93ff-3d486243876b.jpg)

Let me know what other info you need to troubleshoot this. Thank you!

**Comment by SANdood** [comment]
I just posted updates that should fix your issues - please see https://community.hubitat.com/t/release-universal-ecobee-suite-version-1-8-01/34839/265?u=storageanarchy . Let me know so I can close this issue...

**Comment by Mythris29** [comment]
Ran the update and the dropdowns work until I setup humidity sensors which is strange.

I got this error

Unexpected Error
An unexpected error has occurred trying to load the app. Check Logs for more information.
Error: Ambiguous method overloading for method java.math.BigDecimal#plus. Cannot resolve which method to invoke for [null] due to overlapping prototypes between: [class java.lang.Character] [class java.lang.String] [class java.lang.Number] [class java.math.MathContext]

I'll attach screenshots to try to explain what works and what doesn't

All of the dropdowns work still at this point
![ecobee2](https://user-images.githubusercontent.com/15204330/98572377-cca65100-2272-11eb-9c98-be12697645c8.jpg)

I select my humidity sensors...
![ecobee3](https://user-images.githubusercontent.com/15204330/98572392-d039d800-2272-11eb-8cb0-5092a88cd0c7.jpg)

And then if I try to use any of the dropdowns the GUI crashes and gives me that blank screen (or that error I pasted here...but that only happened once)
![ecobee4](https://user-images.githubusercontent.com/15204330/98572414-d465f580-2272-11eb-8473-5ff3d67ed462.jpg)

Okay after I wrote all this out I did find something else that might be useful. The dropdowns not working only happens if I select multiple humidity sensors. They seem to still work if I only select one.

**Comment by SANdood** [comment]
The only sensors listed that supply Humidity are the ones named "EcobeeTherm: Ecobee" and "EcobeeSensor: Ecobee (Thermostat)". Ecobee remote sensors do not provide humidity (only temperature and occupancy/motion). The Device Driver for remote sensors have to assert that they support relativeHumidity (even though the sensor doesn't) because I use the same driver for both remote sensors and the thermostat-as-a-sensor.

I'll see what I can do to prevent the silent failure, but until then, please only select the thermostat device or the thermostat-as-a-sensor device (no need to select them both as they are in fact the same device).

Enjoy!

**Comment by Mythris29** [comment]
Ah okay that makes sense. Once I just used the thermostat (the only real humidity sensor evidently) it worked! Thank you for your help with this and the quick updates.
