### ISSUE TITLE
Ecobee Smartbuildings

### ISSUE THREAD

**Issue by kevincrots** [SANdood/Ecobee-Suite#60]
Are there plans to incorporate the Ecobee Smartbuildings functionality into the Hubitat driver since Ecobee is forcing everyone who has a commercial EMS account to switch to Smartbuildings?

**Comment by SANdood** [comment]
No plans, because I don’t know anything about SmartBuildings or commercial accounts. If it is something simple, I’m happy to try to add support, but I will need someone to help me figure out the changes, and test the resulting code...

**Comment by kevincrots** [comment]
In the Ecobee Suite there is a commercial selection option which routes you to authentication for the ecobee EMS.  The EMS is being sunsetted and they are forcing everyone over to the new Smart Buildings environment.  The API can be found here:  https://docs.sb.ecobee.com/.

**Comment by kevincrots** [comment]
I wanted to follow-up on this and see if there will be support for smartbuildings in the next revision.  Ecobee is pushing customers from the commercial EMS platform to Smartbuildings and I was wondering if this would migrate there eventually.  Appreciate it.

**Comment by SANdood** [comment]
I still have no plans because I still have no way to test the code, and the changes required appear to be extensive.

**Comment by kevincrots** [comment]
If you need a way to test, I can support if needed.  I have accounts and a Hubitat.

Thanks

Kevin

**Comment by SANdood** [comment]
My apologies, but the code changes required are far too extensive for me to undertake at this time. Pretty much would require a ground-up reimplementation.

**Comment by kevincrots** [comment]
Appreciate the update.  I didn’t realize they had done a complete  ground-up change.  Thanks for investigating.

Kevin
