### ISSUE TITLE
Contacts & Switches not working 

### ISSUE THREAD

**Issue by oliversierrab** [SANdood/Ecobee-Suite#7]
Contacts & Switches 1.6.13 won't let me set up the smart app, it always shows a 'something went wrong' is there any additional setting I need to do? Thanks

**Comment by SANdood** [comment]
1) Please report issue on the SmartThings thread: https://community.smartthings.com/t/release-free-ecobee-suite-version-1-6-1/132248 

2) I cannot reproduce - what settings are you using?

3) If you open live logging in the IDE when you try to save, there will probably be some helpful info in there for the SmartApp...let me know what it says and I'll try to track it down...

**Comment by oliversierrab** [comment]
Thanks, I've re-installed the handler and it works now.
