### ISSUE TITLE
Installation error when Alexa SmartApp is installed and "Allow Alexa to access all devices" is turned on

### ISSUE THREAD

**Issue by aifreedom** [SANdood/Ecobee-Suite#8]
Ecobee Suite Manager version: 1.6.16

When Alexa SmartApp is installed and "Allow Alexa to access all devices" is turned on, after saving the OAuth credentials, I get an error `physicalgraph.exception.ConflictException: Device still in use. Remove from any SmartApps or Dashboards, then try again @line -1 (doCall)` in the log. 

The error happens because the two test device created in the installation process are in use by the Alexa app. I'm not really sure how to fix it in code. My workaround is to turn off that switch in the Alexa app temporarily, finish my Ecobee app installation, and turn it back on.

**Comment by SANdood** [comment]
I will update the documentation to note that the Alexa app can "silently' subscribe to the test devices when it is configured to support ALL ST devices (bad behavior of the Alexa app, IMHO).
