### ISSUE TITLE
Question about Hubitat Integration

### ISSUE THREAD

**Issue by ryancasler** [SANdood/Ecobee-Suite#9]
I was wondering if your DTH would work alone without the suite manager or other apps.  Basically, I am looking for a driver that I would be able to send the "setProgram" command from.  I have moved to Hubitat and that isn't available in their native ecobee supported driver.  

Thanks,
Ryan

**Comment by SANdood** [comment]
The current version will not run on hubitat. Someone has published a port of v1.4.* somewhere for hubitat, but I have not made any attempt to support it, as I have no way to test/qualify it.
